language: r
cache: packages
r_check_args: --no-build-vignettes --no-manual
notifications:
  slack: googleauthrverse:tGfXjSD58cQSEr1YuzQ5hKPS
  email:
    on_success: change
    on_failure: change
r_packages:
- knitr
- covr
- drat
- readr
after_success:
- Rscript -e 'library("covr");codecov(line_exclusions = list("R/options.R","R/utilities.R"))'
